# Generated by Django 4.2.27 on 2026-01-30 14:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import medicoes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('geosciences', 'Geociências'), ('metrology', 'Metrologia'), ('physics', 'Física'), ('defense', 'Defesa'), ('science_communication', 'Divulgação Científica')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Área de Atuação',
                'verbose_name_plural': 'Áreas de Atuação',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='viewer', help_text='Categoria do usuário no sistema', max_length=20, verbose_name='Tipo de Usuário')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organização/Instituição')),
                ('role_category', models.CharField(choices=[('academic', 'Acadêmico'), ('student', 'Estudante'), ('professional', 'Profissional')], default='professional', help_text='Categoria do usuário: acadêmico, estudante ou profissional', max_length=20, verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, related_name='users', to='medicoes.areaofexpertise')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoGravimetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estacao', models.CharField(help_text='Nome identificador da estação gravimétrica', max_length=200, verbose_name='Nome da Estação')),
                ('codigo_estacao', models.CharField(help_text='Código único da estação', max_length=50, unique=True, verbose_name='Código da Estação')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude em graus decimais', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude (graus)')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude em graus decimais', max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude (graus)')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Altitude em metros acima do nível do mar', max_digits=8, null=True, verbose_name='Altitude (m)')),
                ('valor_gravidade', models.DecimalField(decimal_places=5, help_text='Valor da gravidade em miligals', max_digits=12, verbose_name='Valor da Gravidade (mGal)')),
                ('incerteza', models.DecimalField(blank=True, decimal_places=5, help_text='Incerteza da medição em miligals', max_digits=8, null=True, verbose_name='Incerteza (mGal)')),
                ('anomalia_bouguer', models.DecimalField(blank=True, decimal_places=5, help_text='Anomalia de Bouguer em miligals (calculada automaticamente)', max_digits=12, null=True, verbose_name='Anomalia de Bouguer (mGal)')),
                ('densidade_referencia', models.DecimalField(decimal_places=3, default=2.67, help_text='Densidade utilizada no cálculo (padrão: 2.67 g/cm³)', max_digits=6, verbose_name='Densidade de Referência (g/cm³)')),
                ('data_medicao', models.DateField(help_text='Data em que a medição foi realizada', verbose_name='Data da Medição')),
                ('operador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador')),
                ('instrumento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instrumento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('foto_estacao', models.ImageField(blank=True, help_text='Foto da estação gravimétrica (máx. 5MB)', null=True, upload_to='estacoes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), medicoes.models.validar_imagem_tamanho], verbose_name='Foto da Estação')),
                ('croqui', models.ImageField(blank=True, help_text='Croqui ou desenho técnico da estação (máx. 5MB)', null=True, upload_to='croquis/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), medicoes.models.validar_imagem_tamanho], verbose_name='Croqui/Desenho da Estação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário responsável pela medição', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Medição Gravimétrica',
                'verbose_name_plural': 'Medições Gravimétricas',
                'ordering': ['-data_medicao', 'nome_estacao'],
                'indexes': [models.Index(fields=['codigo_estacao'], name='medicoes_me_codigo__657d76_idx'), models.Index(fields=['data_medicao'], name='medicoes_me_data_me_178b2a_idx')],
            },
        ),
    ]
