# Generated by Django 4.2.27 on 2026-02-02 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='densidade_referencia',
            field=models.DecimalField(decimal_places=6, default=2.67, help_text='Densidade utilizada no cálculo (padrão: 2.67 g/cm³)', max_digits=6, verbose_name='Densidade de Referência (g/cm³)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude em graus decimais', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude (graus)'),
        ),
    ]
