# Generated by Django 4.2.27 on 2026-02-02 13:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import medicoes.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0002_alter_medicaogravimetrica_densidade_referencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='medicaogravimetrica',
            options={'verbose_name': 'Medição Gravimétrica', 'verbose_name_plural': 'Medições Gravimétricas'},
        ),
        migrations.RemoveIndex(
            model_name='medicaogravimetrica',
            name='medicoes_me_codigo__657d76_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicaogravimetrica',
            name='medicoes_me_data_me_178b2a_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role_category',
            field=models.CharField(choices=[('academic', 'Acadêmico'), ('student', 'Estudante'), ('professional', 'Profissional')], default='professional', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='viewer', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='altitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='anomalia_bouguer',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='codigo_estacao',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='croqui',
            field=models.ImageField(blank=True, null=True, upload_to='croquis/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), medicoes.models.validar_imagem_tamanho]),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='data_medicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='densidade_referencia',
            field=models.DecimalField(decimal_places=6, default=Decimal('2.670000'), max_digits=10, verbose_name='Densidade (g/cm³)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='foto_estacao',
            field=models.ImageField(blank=True, null=True, upload_to='estacoes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), medicoes.models.validar_imagem_tamanho]),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='incerteza',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='instrumento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='nome_estacao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='operador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='valor_gravidade',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Gravidade (mGal)'),
        ),
    ]
