# Generated by Django 4.2.27 on 2026-02-02 13:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import medicoes.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='medicaogravimetrica',
            options={'ordering': ['-data_medicao', 'nome_estacao'], 'verbose_name': 'Medição Gravimétrica', 'verbose_name_plural': 'Medições Gravimétricas'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organização/Instituição'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role_category',
            field=models.CharField(choices=[('academic', 'Acadêmico'), ('student', 'Estudante'), ('professional', 'Profissional')], default='professional', help_text='Categoria do usuário: acadêmico, estudante ou profissional', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='viewer', help_text='Categoria do usuário no sistema', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='altitude',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altitude em metros acima do nível do mar', max_digits=8, null=True, verbose_name='Altitude (m)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='anomalia_bouguer',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Anomalia de Bouguer em miligals (calculada automaticamente)', max_digits=12, null=True, verbose_name='Anomalia de Bouguer (mGal)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='codigo_estacao',
            field=models.CharField(help_text='Código único da estação', max_length=50, unique=True, verbose_name='Código da Estação'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='croqui',
            field=models.ImageField(blank=True, help_text='Croqui ou desenho técnico da estação (máx. 5MB)', null=True, upload_to='croquis/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), medicoes.models.validar_imagem_tamanho], verbose_name='Croqui/Desenho da Estação'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='data_medicao',
            field=models.DateField(help_text='Data em que a medição foi realizada', verbose_name='Data da Medição'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='densidade_referencia',
            field=models.DecimalField(decimal_places=3, default=2.67, help_text='Densidade utilizada no cálculo (padrão: 2.67 g/cm³)', max_digits=6, verbose_name='Densidade de Referência (g/cm³)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='foto_estacao',
            field=models.ImageField(blank=True, help_text='Foto da estação gravimétrica (máx. 5MB)', null=True, upload_to='estacoes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), medicoes.models.validar_imagem_tamanho], verbose_name='Foto da Estação'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='incerteza',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Incerteza da medição em miligals', max_digits=8, null=True, verbose_name='Incerteza (mGal)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='instrumento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instrumento'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude em graus decimais', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude (graus)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Longitude em graus decimais', max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude (graus)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='nome_estacao',
            field=models.CharField(help_text='Nome identificador da estação gravimétrica', max_length=200, verbose_name='Nome da Estação'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='operador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pela medição', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='valor_gravidade',
            field=models.DecimalField(decimal_places=5, help_text='Valor da gravidade em miligals', max_digits=12, verbose_name='Valor da Gravidade (mGal)'),
        ),
        migrations.AddIndex(
            model_name='medicaogravimetrica',
            index=models.Index(fields=['codigo_estacao'], name='medicoes_me_codigo__657d76_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaogravimetrica',
            index=models.Index(fields=['data_medicao'], name='medicoes_me_data_me_178b2a_idx'),
        ),
    ]
