# Generated by Django 4.2.28 on 2026-02-12 11:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaogravimetrica',
            name='marker_custom_url',
            field=models.URLField(blank=True, help_text='Informe a URL completa para um ícone personalizado quando escolher "URL personalizada".', max_length=500, null=True, verbose_name='URL do Ícone Personalizado'),
        ),
        migrations.AddField(
            model_name='medicaogravimetrica',
            name='marker_icon',
            field=models.CharField(choices=[('default', 'Padrão (azul)'), ('red', 'Vermelho'), ('green', 'Verde'), ('orange', 'Laranja'), ('purple', 'Roxo'), ('dark', 'Escuro'), ('custom', 'URL personalizada')], default='default', help_text='Selecione o estilo do marcador a ser exibido no mapa (apenas para administradores)', max_length=50, verbose_name='Ícone do Marcador'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='densidade_referencia',
            field=models.DecimalField(decimal_places=3, default=Decimal('2.670'), max_digits=6, verbose_name='Densidade de Referência (g/cm³)'),
        ),
    ]
