# Generated by Django 4.2.28 on 2026-02-23 14:14

from django.db import migrations, models
import medicoes.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0005_medicaogravimetrica_marker_custom_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro Pendente',
                'verbose_name_plural': 'Registros Pendentes',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Endereço de email do usuário (único)', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='valor_gravidade',
            field=models.DecimalField(decimal_places=5, help_text='Valor da gravidade em miligals', max_digits=12, validators=[medicoes.models.validar_gravidade_range], verbose_name='Valor da Gravidade (mGal)'),
        ),
    ]
